### PR TITLE
Add COC link, use SVG in footer

### PR DESCRIPTION
**Pull request by astronomersiva**

### CODE REVIEW

**Comment by bravegnu** [comment]
I get this, when I run jekyll serve. I am using the Debian Jessie version of jekyll 2.2.0.

`Liquid Exception: Unknown tag 'include_relative' in _includes/footer.html, included in _layouts/page.html`

**Comment by bravegnu** [comment]
And if I try to install the latest version of jekyll, I get his:
```
ERROR:  Error installing jekyll:
	ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.
```

**Comment by astronomersiva** [comment]
I am running Jekyll 3.7.2...and GH Pages has Jekyll 3.7.3. I guess you will have to update Ruby then 🤔

**Comment by astronomersiva** [comment]
If you would like to quickly take a preview without updating, I would suggesting moving the SVGs to `_include`, changing `include_relative` to `include` and removing `img/` from the params.

**Comment by bravegnu** [comment]
The COC link actually opens up in a text editor. :-/

**Comment by bravegnu** [comment]
> The COC link actually opens up in a text editor. :-/

It is more likely to be an issue with jekyll serve.

**Comment by shrayasr** [comment]
`<Yak shaving in progress> `

Sigh. Why aren't these things easier 🤦‍♂️ 

Probably cc in @zerothabhishek to help with Ruby/Jekyll?

**Comment by zerothabhishek** [comment]
Installing Ruby just for this is too much of a hassle. We can use one of the test servers instead (where I had set-up Junction) @shrayasr @bravegnu

**Comment by astronomersiva** [comment]
You should be able to see the changes here - https://astronomersiva.github.io/website-1/

**Review by bravegnu — APPROVED** [review]

**Pull request merged**
