### PR TITLE
Add sponsors list

### PR DESCRIPTION
**Pull request by astronomersiva**
* Moved FAQ to a separate page to make space in the index file.
* Added sponsors.

Preview here - https://astronomersiva.github.io/website-1/

There are issues in navigating to faq and coc in this preview link as I am serving from https://astronomersiva.github.io/website-1/ instead of https://astronomersiva.github.io/. This shouldn't be an issue when merged.

### CODE REVIEW

**Comment by astronomersiva** [comment]
I am trying to create the sponsors list based on a YML file. Will be easier to add new sponsors if that is done. Having some difficulties in aligning img and svg 🤕.

**Comment by bravegnu** [comment]
I would prefer the logos to be larger. Examples: https://2017.pyconuk.org/ https://us.pycon.org/2018/

**Comment by astronomersiva** [comment]
Changed and pushed. Please check.

**Comment by bravegnu** [comment]
A few fixes. The Sponsor Button, could be renamed to "Sponsorship Prospectus". And lets add OrangeScape logo as well.

**Comment by astronomersiva** [comment]
Made the requested changes.

**Comment by bravegnu** [comment]
Oops! Just noticed that the logos are not linked to the company's website:

  * Pipal Academy - http://pipal.in/
  * OrangeScape - http://orangescape.com/
  * Clay Labs - http://claylabs.com/
  * Zilogic Systems - http://zilogic.com/

**Comment by bravegnu** [comment]
Also can you check the other OrangeScape logo? This variant looks jarring.

**Comment by shrayasr** [comment]
OT: Let's work off branches in this repo viz a viz forking off? That way we all can make changes collaboratively and not just depend on the person proposing the change? 

cc @zerothabhishek

**Comment by astronomersiva** [comment]
I have added the hyperlinks.

This is how the other logo looks like.

screen shot 2018-05-06 at 10 21 48 pm

**Review by shrayasr — APPROVED** [review]

**Pull request merged**
