### PR TITLE
Move to Jekyll

### PR DESCRIPTION
**Pull request by astronomersiva**

### CODE REVIEW

**Comment by astronomersiva** [comment]
@shrayasr Please check this once.

**Comment by shrayasr** [comment]
How'd you like me to review this @astronomersiva?

**Comment by astronomersiva** [comment]
@shrayasr Please check if I have missed something..I have moved `cobc.html` to `pysangamam.org/code-of-business-conduct`. I believe this hasn't been shared with anyone till now. I have left the sponsorship brochure at the same url.

**Comment by astronomersiva** [comment]
Also, this ;)

screen shot 2018-04-29 at 3 12 10 pm

**Comment by shrayasr** [comment]
> Please check if I have missed something..I have moved cobc.html to pysangamam.org/code-of-business-conduct. 

As long as everything works as is, that's good.

> I believe this hasn't been shared with anyone till now. I have left the sponsorship brochure at the same url.

Its not linked from the main page. It must be.

**Comment by shrayasr** [comment]
> Also, this ;)

Would you prefer we remove this? Thought its slightly better to have it given we might have more contributions

**Review by shrayasr — APPROVED** [review]

**Comment by shrayasr** [comment]
Approved @astronomersiva. Can you merge? :shipit:

**Comment by astronomersiva** [comment]
@shrayasr I also prefer having this enabled.

**Pull request merged**
