### PR TITLE
 Add keynote section

### PR DESCRIPTION
**Pull request by astronomersiva**

### CODE REVIEW

**Comment by shrayasr** [comment]
LGTM. I'll send you the picture and bio right away and we'll merge it in with the live changes?

**Comment by astronomersiva** [comment]
@shrayasr done

**Comment by shrayasr** [comment]
Can we push this + the blog for keynote speaker together?

**Comment by astronomersiva** [comment]
Shall I push the blog today evening? I am at work now.

**Comment by shrayasr** [comment]
> Shall I push the blog today evening? I am at work now.

Yes sir :)

**Comment by astronomersiva** [comment]
Done @shrayasr

**Review by shrayasr — APPROVED** [review]

**Comment by shrayasr** [comment]
@astronomersiva can you handle the conflicts here? Then I'll merge

**Comment by astronomersiva** [comment]
Rebased 👍

**Pull request merged**
